title: "Mission: Liberty"
email: info@missionliberty.ee
description: >- # this means to ignore newlines until "baseurl:"
  Mission: Liberty is advancing liberty through targeted initiatives.
  Join us Wednesday nights in Tallinn, Estonia for weekly debates.
url: "https://www.missionliberty.ee"
#twitter_username: missionliberty.ee
#github_username:  MissionLiberty

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
   - README.md